### ISSUE TITLE
Suspend not working properly on TC21

### ISSUE THREAD

**Issue by jsroest** [darryncampbell/DataWedge-Quick-Suspend-Scanner#1]
Hi Darryn,

I experience the issue that the scanner is not always suspended after calling suspend on the TC21. To eliminate the possibility that the problem is in my Flutter app, I've tried your sample and it shows the same irratic behavior on the TC21.

I can not reproduce this on the TC57, so it seems like a problem specific to the TC21. I've upgraded the TC21 to the latest version.

I know that the scanner has to be in the 'Scanning' or 'Waiting' state, I check for that explicitly.

I have filed an issue at Zebra support, but I thought that I could contact you directly, to speed things up. You can easily check and confirm this behavior yourself if you try your sample app with a TC21. It will only take a few minutes.

Regards,
Sander

**Comment by darryncampbell** [comment]
You are overestimating my influence with the support team 😄  Can you email me with the case number and who you are dealing with in support (contact details can be found at https://darryncampbell.co.uk/index.html#contact) & I'll see what I can do.

**Comment by jsroest** [comment]
Haha, never underestimate yourself ;-)

LifeGuard Update 79 (released 10-June-2021)
SPR41725 - Resolved an issue where intermittently DataWedge would scan barcodes even when in suspend state.

Thanks

**Comment by darryncampbell** [comment]
Great, glad it got resolved
